const { SlashCommandBuilder, AttachmentBuilder, EmbedBuilder } = require('discord.js');
const fetch = require('node-fetch')

async function query(data) {
    const response = await fetch(
        "https://api-inference.huggingface.co/models/prompthero/openjourney-v4",
        {
            headers: { Authorization: "Bearer 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" },
            method: "POST",
            body: JSON.stringify(data),
        }
    );
    const result = await response.blob();
    return result;
}

module.exports = {
    data: new SlashCommandBuilder()
        .setName('art')
        .setDescription('Replies with image!')
        .addStringOption(option =>
            option.setName('text')
                .setDescription('The text of the image you want.')
                .setRequired(true)),
    async execute(interaction) {
        await interaction.deferReply();
        const req = interaction.options.getString('text');
        const respEmbed = new EmbedBuilder()
            .setColor(0x8CD867)
            .setTitle("Art generated by AI.")
            .addFields({ name: "Request", value: req })
            .setImage('attachment://image.jpg');
        let response = await query({ "inputs": req });
        const abuff = await response.arrayBuffer();
        const buf = new Buffer.from(abuff);
        let attachmentBuilder = new AttachmentBuilder(buf, { name: 'image.jpg' });
        interaction.editReply({ embeds: [respEmbed], files: [attachmentBuilder] });
    },
};