const { SlashCommandBuilder, AttachmentBuilder, EmbedBuilder } = require('discord.js');
const fetch = require('node-fetch')
const { openJourneyApi } = require('../config.json');


/**
 * 
 * Make openjourney api call hosted on hugging-face
 * @param {*} data 
 * @returns image according to the input data
 */
async function query(data) {
    const response = await fetch(
        "https://api-inference.huggingface.co/models/prompthero/openjourney-v4",
        {
            headers: { Authorization: openJourneyApi },
            method: "POST",
            body: JSON.stringify(data),
        }
    );
    const result = await response.blob();
    return result;
}

/**
 * returns object containing data about the command
 * and
 * commands execute function which gets executed when this command gets triggered
 * art command takes in text param 
 * and returns an image generated by openjourney of that text
 */
module.exports = {
    data: new SlashCommandBuilder()
        .setName('art')
        .setDescription('Replies with image!')
        .addStringOption(option =>
            option.setName('text')
                .setDescription('The text of the image you want.')
                .setRequired(true)),
    async execute(interaction) {

        // replying initially with defer reply becuase api call takes time and discord expects reply in 3 secs
        await interaction.deferReply();

        //getting the text from command
        const req = interaction.options.getString('text');

        //making an embeded reply
        const respEmbed = new EmbedBuilder()
            .setColor(0x8CD867)
            .setTitle("Art generated by AI.")
            .addFields({ name: "Request", value: req })
            .setImage('attachment://image.jpg');

        //call openjourney
        let response = await query({ "inputs": req });

        //convert blob image to buffer
        const abuff = await response.arrayBuffer();
        const buf = new Buffer.from(abuff);

        //attach image and update the reply
        let attachmentBuilder = new AttachmentBuilder(buf, { name: 'image.jpg' });
        interaction.editReply({ embeds: [respEmbed], files: [attachmentBuilder] });
    },
};